
name: Day 7 - Secrets Demo

on:
  push:
    paths:
      - ".github/workflows/day7-secrets.yml"

jobs:
  secret-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Show the secret
        run: |
          echo "ğŸ” The secret is: ${{ secrets.MY_SECRET_NAME }}"
