name: Day 7 - Secrets and Env Demo

on:
  workflow_dispatch:

jobs:
  show-secrets-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Secret
        run: 'echo "ğŸ” The secret is: ${{ secrets.MY_SECRET_NAME }}"'
